version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 23.9.0
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm i
  build:
    commands:
      - echo Build started on `date`
      - echo Building the application...
      - npm run build
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: dist